modified Last Updated timestamp format
AfricasVoices/Operations-Dashboard pull request #155
Opened 2020-02-04 13:46 UTC by DanielMwendwa

2020-02-10 07:09 UTC, IsaackMwenda requested changes

2020-02-10 07:09 UTC, IsaackMwenda commented on public/graph.js
> +        let fullDateFormat = d3.timeFormat("%d %b %Y %H:%M:%S %p");
make this consistent with message coding table last updated time.

2020-02-13 06:25 UTC, IsaackMwenda commented on public/UI.js
> +            let fullDateFormat = d3.timeFormat("%d %b %Y %H:%M:%S %p"),
Hi @DanielMwendwa I meant to make the graph.js last updated to be consistent with coding progress Last updated: 2020-02-13 06:25:04

2020-02-17 14:36 UTC, IsaackMwenda requested changes
The pushed branch does not contain the changes please fix and request review.

2020-02-19 06:56 UTC, DanielMwendwa commented
@IsaackMwenda please check PR #163

2020-02-19 06:56 UTC, closed without merging