Enable Tooltips for stacked bar graphs
AfricasVoices/Operations-Dashboard pull request #182
Opened 2020-04-01 07:27 UTC by DanielMwendwa

2020-04-06 08:38 UTC, IsaackMwenda requested changes

2020-04-06 08:38 UTC, IsaackMwenda commented on public/graph.js
> +        let operators_identity = {
let us use the mno_colors table available in avf-dashboards firebase.

2020-04-08 09:57 UTC, IsaackMwenda requested changes
Requesting changes because of a question re-color conversion

2020-04-08 09:57 UTC, IsaackMwenda commented on public/graph.js
> +                    let op = legendColorToOperator(hex)
Change to a descriptive variable name, please.

2020-04-08 09:57 UTC, IsaackMwenda commented on public/styles.css
> +.tooltip2 {
```suggestion
.tooltip{	
```
?

2020-04-08 09:57 UTC, IsaackMwenda commented on public/graph.js
> +
```suggestion
```
remove unnecessary white spaces here and in the rest of the code

2020-04-08 09:57 UTC, IsaackMwenda commented on public/graph.js
> +
```suggestion
```

2020-04-08 09:57 UTC, IsaackMwenda commented on public/graph.js
> +                            let num = d.data[`${op}_received`]
```suggestion
                            let total_receved_no = d.data[`${op}_received`]
```
? or better

2020-04-08 09:57 UTC, IsaackMwenda commented on public/graph.js
> +                            let content = `<div>${op} ${num}</div>`
```suggestion
                            let tooltip_content = `<div>${op} ${num}</div>`  
```
?

2020-04-08 09:57 UTC, IsaackMwenda commented on public/graph.js
> +                    let hex = rgbToHex(...rgb)
If operator colors are already stored in hex format, we should probably pull this from the table instead?

2020-04-15 06:41 UTC, DanielMwendwa commented
Issue: having trouble accessing the relevant values of the initial dataset for a mousover tooltip
https://github.com/AfricasVoices/Operations
Reason: `d` is the Array[2] at this point with the values defining baseline / topline, `d.data` is the complete original data object but is missing the information over which stack of the series I'm currently hovering.
Solution:  Get the name of the element accessing the parent's data, and using that name to get the value
Dashboard/pull/182/commits/ba5229a175ffe228f529157a5b790d4e2ed98a13

2020-04-15 11:37 UTC, IsaackMwenda commented on public/graph.js
> +                                receivedDay = d.data.day,
no need for the date info because it is already rep in the axes.

2020-04-15 12:06 UTC, DanielMwendwa commented
Updated tooltip content by removing date info

2020-04-15 13:14 UTC, IsaackMwenda approved these changes
Great this LGTM! @DanielMwendwa. Its also going to be really useful. My only concern now is the duplication of the code once we apply this to outgoing and failed graphs. We might need to apply OOP for graph.js soon. An issue, for now, is okay. Thanks.

2020-04-15 13:14 UTC, IsaackMwenda commented on public/graph.js
> +                            let receivedMessages = d.data[operatorReceived],
operatorReceived?

2020-04-15 13:14 UTC, IsaackMwenda commented on public/graph.js
> +                                receivedDay = d.data.day,
we no longer need this variable

2020-04-15 13:14 UTC, IsaackMwenda commented on public/graph.js
> +                                tooltipContent = `<div>${operatorName.charAt(0).toUpperCase() + operatorName.slice(1)}</div>`;
28 (70%) Hormuud Messages?

2020-04-15 13:31 UTC, DanielMwendwa commented on public/graph.js
> +                            let receivedMessages = d.data[operatorReceived],
I'll update to `operatorNameWithMessageDirection` because it's the operator name concatenated with the msg direction

2020-04-15 14:03 UTC, merged

2020-04-15 14:04 UTC, DanielMwendwa commented
Thanks @IsaackMwenda