Javascript Modules
AfricasVoices/Operations-Dashboard pull request #237
Opened 2020-05-26 07:36 UTC by DanielMwendwa

2020-06-05 07:15 UTC, IsaackMwenda requested changes
Hi Daniel please resolve conflicts

2020-06-11 07:37 UTC, DanielMwendwa commented
conflicts resolved

2020-06-16 11:32 UTC, IsaackMwenda approved these changes

2020-06-16 11:32 UTC, IsaackMwenda commented on public/app.js
> +            .addEventListener("click", () => {import("./auth.js").then(module => {
Why are dynamically importing this? It is used twice so cleaner if imported statically.

2020-06-16 11:32 UTC, IsaackMwenda commented on public/graph.js
> +export class GraphController {
please delete before merging.

2020-06-16 12:00 UTC, DanielMwendwa commented on public/app.js
> +            .addEventListener("click", () => {import("./auth.js").then(module => {
Updated thanks.

2020-06-16 12:02 UTC, DanielMwendwa commented on public/graph.js
> +export class GraphController {
Deleted  graph.js file

2020-06-16 12:03 UTC, merged