changed legend colors for imaqal graphs
AfricasVoices/Operations-Dashboard pull request #83
Opened 2019-10-11 14:09 UTC by DanielMwendwa

![Screenshot from 2019-10-11 17-06-48](https://user-images.githubusercontent.com/39700595/66658256-c72e9f80-ec49-11e9-9f34-ec58700a970d.png)
Fixes: #77

2019-10-17 06:37 UTC, IsaackMwenda requested changes

2019-10-17 06:37 UTC, IsaackMwenda commented on public/media_engagement/imaqal_media_engagement.js
> +    color_scheme = ["#e6194B", "#f58231", "#3cb44b", "#CCCC00", "#4363d8", "#800000", "#f032e6", "#911eb4"]
please upload a screenshot of  the new changes and request re-review

2019-10-17 08:51 UTC, DanielMwendwa commented
![legends](https://user-images.githubusercontent.com/39700595/66993561-ab9d1c00-f0c3-11e9-8037-34cc08d4cc56.PNG)

2019-10-17 13:35 UTC, IsaackMwenda approved these changes
Thanks @DanielMwendwa

2019-10-18 08:01 UTC, lukechurch approved these changes
Thanks @DanielMwendwa

2019-10-18 13:04 UTC, merged