Changed the coding progress navbar and the layout of the body to work…
AfricasVoices/Operations-Dashboard pull request #85
Opened 2019-10-22 08:35 UTC by DanielMwendwa

![coding_progress](https://user-images.githubusercontent.com/39700595/67269762-f81b9980-f4bf-11e9-8f0c-6186214c4b64.png)
… with bootstrap

2019-10-25 13:37 UTC, IsaackMwenda requested changes

2019-10-25 13:37 UTC, IsaackMwenda commented on public/coda/styles.css
> -    height: 30px;
I think we need to control the heading height

2019-10-25 13:37 UTC, IsaackMwenda commented on public/coda/styles.css
> -    font-size:15;
ditto

2019-10-25 13:37 UTC, IsaackMwenda commented on public/coda/styles.css
> -    font-size:16;
ditto

2019-10-27 19:46 UTC, DanielMwendwa commented on public/coda/styles.css
> -    font-size:15;
Done

2019-10-31 13:25 UTC, IsaackMwenda requested changes
please fix merge conflicts

2019-10-31 13:25 UTC, IsaackMwenda commented on public/coda/styles.css
> +    font-size: 16;
please be consistent with the var spacing

2019-10-31 13:25 UTC, IsaackMwenda commented on public/coda/styles.css
> -.container {
As discussed offline please variate the container width and margins for different screen sizes. It feels a bit compressed in extra-large screens and the graphs overlay the operator legend.

2019-11-06 13:19 UTC, IsaackMwenda commented
@DanielMwendwa whats the progress on this?

2019-11-06 22:34 UTC, DanielMwendwa commented on public/coda/styles.css
> +    font-size: 16;
Okay

2019-11-06 22:50 UTC, DanielMwendwa commented on public/coda/styles.css
> -.container {
you can now look at the container width on extra-large screens

2019-11-07 06:09 UTC, IsaackMwenda approved these changes
Thanks, @DanielMwendwa. WorldBank-PLR_recently_displaced text is overflowing. We might need to increase the Dataset row width but in another pr.

2019-11-07 06:09 UTC, IsaackMwenda commented on public/coda/styles.css
> +}
Please add a new line at the end of the file.

2019-11-07 06:29 UTC, merged

2019-11-07 09:00 UTC, DanielMwendwa commented
I had in mind to break this pr into smaller ones but since the changes are dependent on one another I have resolved to leave it like this.