default to 10 min view
AfricasVoices/Operations-Dashboard pull request #95
Opened 2019-11-01 09:06 UTC by DanielMwendwa

Closes: #66

2019-11-01 13:44 UTC, IsaackMwenda requested changes
This still defaults to 1 day for me. Have you tested it?

2019-11-01 13:52 UTC, IsaackMwenda commented
> This still defaults to 1 day for me. Have you tested it?

Sorry had not checkout the branch :)

2019-11-01 13:56 UTC, IsaackMwenda approved these changes
Thanks @DanielMwendwa

2019-11-06 07:59 UTC, lukechurch approved these changes

2019-11-06 21:02 UTC, merged